### ISSUE TITLE
Complete Authentication Flow

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Quizzer#52]
---
### This issue holds the complete details of the requirements for authentication flow for the application. 
---

## Requirement
For this application, we will be supporting 3 main login features, **Google**, **GitHub**, **Local**. Any user can use one of the three options for signing up for our services. If in the future the user sign ups with any other choice other than the one that he had used previously, we have to update data in the database accordingly. For **Local** signup we will be using JWT tokens . 

## User Model 
With all the above login features will be storing these data for our user model
- username 
- email 
- password if using local signup 
- avatar from Google or Github API. default avatar if using local signup 
- unique id for every user

# TODO 
- [ ] Google Authentication Flow
- [ ] Github Authentication Flow
- [x] Local Authentication Flow with jwt token

**Comment by Souvikns** [comment]
We have completed the local authentication system.

**Comment by Souvikns** [comment]
closing this epic, for now, might reopen it in the future.
