### ISSUE TITLE
Local Authentication flow 

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Quizzer#55]
Create local authentication with a unique username and password. User JWT to managing client-side authentication and authorization. 

## TODO
- [x] Create routes for local login and signup 
- [x] Create a user model that supports current local authorization. Also, the model should be able to change in the future. 
- [x] Write controller logic for creating and managing JWT tokens. 
- [x] Write middleware with help of `passport.js`

> connected issues #52

**Comment by Souvikns** [comment]
All of the tasks have been completed.
